version: '3.7'
services:
  localstack:
    networks:
      - user-management
    image: localstack/localstack
    container_name: user-management_localstack
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    ports: 
      - "4566:4566"
      - "4572:4572"
      - "4576:4576"
      - "8080:8080"
    volumes:
      - "./.localstack/init:/docker-entrypoint-initaws.d"
  mongodb:
    networks:
      - user-management
    image: mongo:5.0.0
    container_name: user-management_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    depends_on:
      - localstack
  api:
    networks:
      - user-management
    container_name: user-management_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: local
    ports:
      - 7000:7000
    depends_on:
      - mongodb
networks:
  user-management:
   name: user-management